CREATE TABLE IF NOT EXISTS CONTENT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    URL VARCHAR(255),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    TYPE VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255) NOT NULL
);

INSERT INTO CONTENT(TITLE, DESCRIPTION, URL, CREATED_AT, UPDATED_AT, TYPE, STATUS)
VALUES ('Awesome Spring', 'How to write Awesome applications with Spring', 'http://localhost/spring', CURRENT_TIMESTAMP(), NULL, 'ARTICLE', 'IDEA');